name: Keep Alive
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  keep-alive:
    name: Keep alive, make a dummy commit when needed, to prevent Github blocking workflows
    runs-on: ubuntu-latest
    steps:
      - run: echo $(date +"%T") > dummy.txt
      - run: git commit -am "Dummy commit"
      - run: git push
