name: Keep Alive
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  keep-alive:
    name: Keep alive, make a dummy commit when needed, to prevent Github blocking workflows
    runs-on: ubuntu-latest
    steps:
      - name: Dummy-update
        run: git commit --allow-empty -m "Dummy"

