name: Keep Alive
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Keep alive, make a dummy commit when needed, to prevent Github blocking workflows
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Script
        run: >
          echo $(date +"%T") > dummy.txt;
          git commit -am "Dummy commit";
          git push;
