name: Keep Alive
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  keep-alive:
    name: Keep alive, make a dummy commit when needed, to prevent Github blocking workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
