name: Task
on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Script
        run: >
          chmod +x main/media_script.sh;
          cd main;
          ./media_script.sh;
