name: Task
on:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Chmod
        run: chmod +x media_script.sh
      - name: Execute script
        run: bash media_script.sh
