name: Task
on:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: mishra-ankit/media-generator
          token: ${{ secrets.TOKEN }} 
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: Execute script
        run: bash run.sh
