name: Video Task
on:
  schedule:
    - cron:  '0 */8 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MEDIA_GENERATOR: ${{ secrets.MEDIA_GENERATOR }}
        run: >
          chmod +x main/media_script_1.sh;
          cd main;
          ./media_script_1.sh;
  generate2:
    runs-on: ubuntu-latest
    name: Generate Video 2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MEDIA_GENERATOR: ${{ secrets.MEDIA_GENERATOR }}
        run: >
          chmod +x main/media_script_2.sh;
          cd main;
          ./media_script_2.sh;
  generate3:
    runs-on: ubuntu-latest
    name: Generate Video 3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MEDIA_GENERATOR: ${{ secrets.MEDIA_GENERATOR }}
        run: >
          chmod +x main/media_script_3.sh;
          cd main;
          ./media_script_3.sh;
