name: Task
on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Execute script
        run: bash chmod +x media_script.sh & ./media_script.sh
