name: Task
on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: mishra-ankit/media-generator
          token: ${{ secrets.TOKEN }}
      - name: Install node 16
        shell: bash -l -eo pipefail {0}
        run: nvm install 16.14.0
      - name: Switch to node16
        shell: bash -l -eo pipefail {0}
        run: nvm use 16.14.0
      - name: Install dependencies
        run: |
         sudo apt-get update
         sudo apt install ffmpeg
      - name: NPM Install
        run: npm ci
      - name: Permission
        run: chmod +x run.sh
      - name: Run
        run: node ./runner.js --type askRedditStories
      - name: Commit
        if: ${{ always() }}
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: Update
