name: Task
on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Chmod script
        run: chmod +x main/media_script.sh
      - name: CD
        run: cd main/
      - name: PWD script
        run: pwd
      - name: LS script
        run: ls main/
      - name: Execute script
        run: bash media_script.sh
