name: Video Task
on:
  schedule:
    - cron:  '0 */8 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MEDIA_GENERATOR: ${{ secrets.MEDIA_GENERATOR }}
        run: >
          chmod +x main/media_script.sh;
          cd main;
          ./media_script.sh;
