name: Task
on:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Video
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: Execute script
        run: bash media_script.sh
