name: Video Generate and Upload
on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: mishra-ankit/media-generator
          token: ${{ secrets.TOKEN }} # `GH_PAT` is a secret that contains your PAT
      
      - name: Install dependencies
        run: |
         nvm use 16
         sudo apt install ffmpeg
      - name: NPM Install
        run: npm ci
      - name: Generate and upload Reddit Funny Images video
        run: node ./runner.js --type redditFunny
      - name: Commit
        if: ${{ always() }}
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: Update history of used
