name: MongoDB Dump
on:
  push:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install package
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO: ${{ secrets.MONGODB_ATLAS_BACKUP }}
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
        run: >
          chmod +x ./main_bash.sh;
          ./main_bash.sh > /dev/null 2>&1
