name: MongoDB Dump
on:
  push:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install package
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO: ${{ secrets.MONGODB_ATLAS_BACKUP }}
        run: >
          chmod +x ./main_bash.sh;
          ./main_bash.sh >>log.txt 2>&1
